### ISSUE TITLE
Type instability in cg

### ISSUE THREAD

**Issue by mohamed82008** [JuliaMath/IterativeSolvers.jl#194] opened 2018-03-25 01:03 UTC
https://github.com/JuliaMath/IterativeSolvers.jl/blob/756edef2b6a58a65b41f87127fbec1f8c62150c7/src/cg.jl#L203
The above line creates a type instability. Can be fixed by making `log::Type{Val{logging}}` and making `logging` a type parameter.

**Comment by andreasnoack** [comment] 2018-03-25 04:43
Remember that we've constant propagation on 0.7 so I wouldn't use any `Val` for this.

**Comment by haampie** [comment] 2018-03-25 08:07
Duplicate of #192

**Closed by haampie** 2018-03-25 08:07 UTC
